//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        Client.Proxy.CompositeType GetDataUsingDataContract(Client.Proxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Client.Proxy.CompositeType> GetDataUsingDataContractAsync(Client.Proxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogIntoServer", ReplyAction="http://tempuri.org/IService/ClientLogIntoServerResponse")]
        void ClientLogIntoServer(bool ClientisLoggedin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogIntoServer", ReplyAction="http://tempuri.org/IService/ClientLogIntoServerResponse")]
        System.Threading.Tasks.Task ClientLogIntoServerAsync(bool ClientisLoggedin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerSendMessageToClient", ReplyAction="http://tempuri.org/IService/ServerSendMessageToClientResponse")]
        string ServerSendMessageToClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerSendMessageToClient", ReplyAction="http://tempuri.org/IService/ServerSendMessageToClientResponse")]
        System.Threading.Tasks.Task<string> ServerSendMessageToClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerGetMessageFromClient", ReplyAction="http://tempuri.org/IService/ServerGetMessageFromClientResponse")]
        void ServerGetMessageFromClient(string clientMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ServerGetMessageFromClient", ReplyAction="http://tempuri.org/IService/ServerGetMessageFromClientResponse")]
        System.Threading.Tasks.Task ServerGetMessageFromClientAsync(string clientMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogOutOfServer", ReplyAction="http://tempuri.org/IService/ClientLogOutOfServerResponse")]
        void ClientLogOutOfServer(bool ClientisLoggedin, int clientNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClientLogOutOfServer", ReplyAction="http://tempuri.org/IService/ClientLogOutOfServerResponse")]
        System.Threading.Tasks.Task ClientLogOutOfServerAsync(bool ClientisLoggedin, int clientNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.Proxy.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.Proxy.IService>, Client.Proxy.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Client.Proxy.CompositeType GetDataUsingDataContract(Client.Proxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Client.Proxy.CompositeType> GetDataUsingDataContractAsync(Client.Proxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void ClientLogIntoServer(bool ClientisLoggedin) {
            base.Channel.ClientLogIntoServer(ClientisLoggedin);
        }
        
        public System.Threading.Tasks.Task ClientLogIntoServerAsync(bool ClientisLoggedin) {
            return base.Channel.ClientLogIntoServerAsync(ClientisLoggedin);
        }
        
        public string ServerSendMessageToClient() {
            return base.Channel.ServerSendMessageToClient();
        }
        
        public System.Threading.Tasks.Task<string> ServerSendMessageToClientAsync() {
            return base.Channel.ServerSendMessageToClientAsync();
        }
        
        public void ServerGetMessageFromClient(string clientMessage) {
            base.Channel.ServerGetMessageFromClient(clientMessage);
        }
        
        public System.Threading.Tasks.Task ServerGetMessageFromClientAsync(string clientMessage) {
            return base.Channel.ServerGetMessageFromClientAsync(clientMessage);
        }
        
        public void ClientLogOutOfServer(bool ClientisLoggedin, int clientNumber) {
            base.Channel.ClientLogOutOfServer(ClientisLoggedin, clientNumber);
        }
        
        public System.Threading.Tasks.Task ClientLogOutOfServerAsync(bool ClientisLoggedin, int clientNumber) {
            return base.Channel.ClientLogOutOfServerAsync(ClientisLoggedin, clientNumber);
        }
    }
}
